// All the mutation types
export enum MutationTypes {
  SET_FAVORITES = "SET_FAVORITES",
  SET_TRENDING = "SET_TRENDING",
  SET_TOP_RATED = "SET_TOP_RATED",
  SET_TRAILER = "SET_TRAILER",
  SET_RANDOM = "SET_RANDOM",
  SET_CATEGORY = "SET_CATEGORY",
}
